/**
 * 定义 mutation 里用到的方法常量值，统一处理在这里，一般都是业务字符串常量。
 * @type {string}
 */

export const SET_LOADING_DISPLAY = 'SET_LOADING_DISPLAY'

export const SET_SYSTEM_SIDEBAR = 'SET_SYSTEM_SIDEBAR'
export const TOGGLE_SYSTEM_SIDEBAR = 'TOGGLE_SYSTEM_SIDEBAR'
// 切换角色
export const SET_ADMIN_VIEW = 'SET_ADMIN_VIEW'
export const SWITCH_ADMIN_VIEW = 'SWITCH_ADMIN_VIEW'
// user
// export const INIT_USER_INFO = 'INIT_USER_INFO'
export const SET_USER_INFO = 'SET_USER_INFO'
export const CLEAR_USER_INFO = 'CLEAR_USER_INFO'


export const SET_UPLOAD_TOKEN = 'SET_UPLOAD_TOKEN'
export const SET_CREATIVE_GROUP_LIST = 'SET_CREATIVE_GROUP_LIST'

export const SHOW_SYSTEM_ALERT = 'SHOW_SYSTEM_ALERT'
export const HIDE_SYSTEM_ALERT = 'HIDE_SYSTEM_ALERT'

export const SHOW_SYSTEM_CONFIRM = 'SHOW_SYSTEM_CONFIRM'
export const HIDE_SYSTEM_CONFIRM = 'HIDE_SYSTEM_CONFIRM'
export const RESET_SYSTEM_CONFIRM = 'RESET_SYSTEM_CONFIRM';

export const SET_TOAST = 'SET_TOAST'
export const SET_CONT_HEIGHT = 'SET_CONT_HEIGHT'

export const STORE__CATEGORY_ALL = 'STORE__CATEGORY_ALL'
export const STORE__CATEGORY_TAG = 'STORE__CATEGORY_TAG'

export const TOGGLE_MAIN_LOADING = 'TOGGLE_MAIN_LOADING'

